### ISSUE TITLE
Soil Sampler Drill Component

### ISSUE THREAD

**Issue by KLA-Quantum** [olincollege/The-MuNCHER#2]
I've notices that in your SoilSampler.ino file that you have the load cartridge function. I recommend some type of over correction implemented with your code in addition to having some type of extra sensor to consistently obtain the cartridge and not have to adjust the initial tightness of the drill.

**Comment by zaynpatel** [comment]
Do you have any concrete code recommendations that would be helpful - your feedback would be appreciated @KLA-pie.
